In [125]:
#!python -m spacy download en_core_web_md

In [126]:
#import spacy

In [127]:
#embedding_file=spacy.load('en_core_web_md')

In [128]:
#embedding_file('like').vector

In [129]:
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.tokenize import word_tokenize,sent_tokenize
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [130]:
#from nlp import load_dataset
from nltk.tokenize import word_tokenize,sent_tokenize

In [131]:
import numpy as np
import tensorflow as tf

In [132]:
import nltk
import math
import json
import tensorflow_hub as hub
import spacy

In [133]:
nltk.download('punkt')
#nltk.download('gutenberg')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [134]:
from tensorflow.keras.layers import SimpleRNN,GRU,LSTM,Dense,Embedding,InputLayer,Input
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import CategoricalCrossentropy
from tensorflow.keras.losses import CategoricalCrossentropy,categorical_crossentropy
from tensorflow.keras import Model
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from nltk.corpus import gutenberg

In [135]:
data=open("C:/Users/user/Downloads/corpus.txt")
data=data.read()

In [136]:
#data=gutenberg.raw(fileids='austen-emma.txt')

In [137]:
data

"Much more reproductive choice is now available to women, with the ability to chose whether or not to have children, when to have them and in what context, now a reproductive right given to women. This, combined with shifting social and economic opportunities for women, has lead to an increase in the number of childless women, with, in 1991, twice as many saying that they expected to remain childless as in 1986 (Gillespie, 2001). However the anticipated number of children per woman in Europe and the USA is still near or above two (Bongaarts, 1999), showing that many are still having children. In this essay I will explore why women have children, even though there is now more opportunity for them not to, and why those who do not have children do not do so. I will begin by looking at why women do have children, exploring the idea of push and pull in the decision, introduced by Morrell (1994), looking at factors identified as 'pulling' women into motherhood; psychological, social and econ

In [138]:
corpus_list=[]
corpus=sent_tokenize(data)
for sent in corpus:
  corpus_list.append([sent])

In [139]:
corpus

['Much more reproductive choice is now available to women, with the ability to chose whether or not to have children, when to have them and in what context, now a reproductive right given to women.',
 'This, combined with shifting social and economic opportunities for women, has lead to an increase in the number of childless women, with, in 1991, twice as many saying that they expected to remain childless as in 1986 (Gillespie, 2001).',
 'However the anticipated number of children per woman in Europe and the USA is still near or above two (Bongaarts, 1999), showing that many are still having children.',
 'In this essay I will explore why women have children, even though there is now more opportunity for them not to, and why those who do not have children do not do so.',
 "I will begin by looking at why women do have children, exploring the idea of push and pull in the decision, introduced by Morrell (1994), looking at factors identified as 'pulling' women into motherhood; psychological

In [140]:
len(corpus_list)

67

In [141]:
vectorizer = TfidfVectorizer()

In [142]:
X = vectorizer.fit_transform(corpus)

In [143]:
vocab=vectorizer.get_feature_names_out()

In [144]:
len(vocab)

592

In [145]:
embeddings_array=X.toarray().T

In [146]:
pca=PCA(n_components=50)

In [147]:
dense_embeddings=pca.fit_transform(embeddings_array)

In [148]:
embeddings_dict={}

In [149]:
for i in range(len(vocab)):
  embeddings_dict[vocab[i]]=dense_embeddings[i].tolist()

In [150]:
seq_len=10
tokenizer=Tokenizer()
tokenizer.fit_on_texts([data])
x=tokenizer.texts_to_sequences([data])
#x

In [151]:
x[0]

[114,
 33,
 150,
 151,
 12,
 39,
 241,
 2,
 4,
 28,
 6,
 242,
 2,
 115,
 87,
 29,
 13,
 2,
 9,
 5,
 116,
 2,
 9,
 54,
 1,
 7,
 152,
 153,
 39,
 11,
 150,
 243,
 117,
 2,
 4,
 18,
 244,
 28,
 245,
 15,
 1,
 21,
 55,
 16,
 4,
 88,
 118,
 2,
 89,
 246,
 7,
 6,
 119,
 10,
 69,
 4,
 28,
 7,
 247,
 248,
 8,
 25,
 249,
 3,
 17,
 250,
 2,
 90,
 69,
 8,
 7,
 251,
 47,
 56,
 70,
 6,
 252,
 119,
 10,
 5,
 253,
 154,
 7,
 254,
 1,
 6,
 155,
 12,
 156,
 255,
 29,
 256,
 257,
 258,
 259,
 157,
 3,
 25,
 14,
 156,
 30,
 5,
 7,
 18,
 260,
 71,
 43,
 158,
 48,
 4,
 9,
 5,
 159,
 261,
 72,
 12,
 39,
 33,
 262,
 16,
 54,
 13,
 2,
 1,
 48,
 160,
 91,
 23,
 13,
 9,
 5,
 23,
 13,
 23,
 120,
 71,
 43,
 263,
 26,
 92,
 73,
 48,
 4,
 23,
 9,
 5,
 264,
 6,
 57,
 10,
 265,
 1,
 266,
 7,
 6,
 35,
 267,
 26,
 74,
 75,
 92,
 73,
 22,
 161,
 8,
 268,
 4,
 121,
 19,
 269,
 15,
 1,
 21,
 22,
 8,
 76,
 8,
 92,
 73,
 6,
 58,
 10,
 270,
 22,
 162,
 8,
 122,
 34,
 37,
 19,
 1,
 15,
 93,
 71,
 43,
 271,
 272,
 48,
 4,
 23,

In [152]:
len(x[0])

2226

In [153]:
#tokenizer.get_config()

In [154]:
vocab_dict=json.loads(tokenizer.get_config().get('word_index'))

In [155]:
vocab_dict

{'and': 1,
 'to': 2,
 'that': 3,
 'women': 4,
 'children': 5,
 'the': 6,
 'in': 7,
 'as': 8,
 'have': 9,
 'of': 10,
 'a': 11,
 'is': 12,
 'not': 13,
 'are': 14,
 'social': 15,
 'for': 16,
 'they': 17,
 'this': 18,
 'motherhood': 19,
 'it': 20,
 'economic': 21,
 'factors': 22,
 'do': 23,
 'can': 24,
 'many': 25,
 'by': 26,
 'society': 27,
 'with': 28,
 'or': 29,
 'having': 30,
 'personal': 31,
 'also': 32,
 'more': 33,
 'discourses': 34,
 'decision': 35,
 'be': 36,
 'on': 37,
 'may': 38,
 'now': 39,
 'these': 40,
 'seen': 41,
 'natural': 42,
 'will': 43,
 'influence': 44,
 'which': 45,
 'some': 46,
 'gillespie': 47,
 'why': 48,
 'upon': 49,
 'their': 50,
 'complex': 51,
 'provide': 52,
 'feel': 53,
 'them': 54,
 'opportunities': 55,
 '2001': 56,
 'idea': 57,
 'influences': 58,
 'andorka': 59,
 '1978': 60,
 'cited': 61,
 'schoen': 62,
 'et': 63,
 'al': 64,
 '1997': 65,
 'wish': 66,
 'security': 67,
 'lifestyle': 68,
 'childless': 69,
 'however': 70,
 'i': 71,
 'there': 72,
 'at': 73,
 'm

In [156]:
vals=list(vocab_dict.values())
keys=list(vocab_dict.keys())
#keys[vals.index(1)]

In [157]:
vocab_size=len(keys)

In [158]:
vocab_size

605

In [159]:
embedding_array=np.zeros((vocab_size+1,50))
embedding_array.shape

(606, 50)

In [160]:
for word,i in tokenizer.word_index.items():
    if word in embeddings_dict:
        embedding_vector=embeddings_dict[word]
  #if embedding_vector is not None:
    embedding_array[i]=embedding_vector

In [161]:
"""for word,i in tokenizer.word_index.items():
  embedding_vector=embedding_file(word).vector
  if embedding_vector is not None:
    embedding_array[i]=embedding_vector"""

'for word,i in tokenizer.word_index.items():\n  embedding_vector=embedding_file(word).vector\n  if embedding_vector is not None:\n    embedding_array[i]=embedding_vector'

In [162]:
#embedding_array[7306]

In [163]:
len(x[0])

2226

In [164]:
x[0][0:15]

[114, 33, 150, 151, 12, 39, 241, 2, 4, 28, 6, 242, 2, 115, 87]

In [165]:
inner_list=[]
X={}
corpus_length=len(x[0])-seq_len
k=0

for i in range(0,corpus_length,seq_len):
  inner_list.clear()
  for j in range(i,i+seq_len):
    inner_list.append(x[0][j])
  X[k]=inner_list[:]
  k=k+1

In [166]:
#list(X.values())
x_train=[]
y_train=[]
for it in list(X.values()):
  x_train.append(it[0:-1])
  y_train.append(it[-1])

In [167]:
x_train[3]

[150, 243, 117, 2, 4, 18, 244, 28, 245]

In [168]:
len(x_train)

222

In [169]:
X=np.array(x_train)
#input_seq.shape
y=np.array(y_train).reshape(len(y_train),1)
#target=tf.reshape(tf.constant(y_train),[len(y_train),1])

In [170]:
y.shape

(222, 1)

In [171]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)

In [172]:
X_train.shape

(155, 9)

In [173]:
y_train

array([[  9],
       [104],
       [  7],
       [  4],
       [ 51],
       [  1],
       [440],
       [ 19],
       [  3],
       [ 10],
       [  5],
       [ 47],
       [ 30],
       [  5],
       [  7],
       [  5],
       [  2],
       [ 35],
       [406],
       [ 10],
       [ 57],
       [ 44],
       [  2],
       [  9],
       [  7],
       [113],
       [ 36],
       [  1],
       [212],
       [  4],
       [ 36],
       [  1],
       [ 14],
       [  2],
       [156],
       [175],
       [319],
       [ 11],
       [200],
       [  3],
       [454],
       [218],
       [141],
       [580],
       [ 14],
       [427],
       [  3],
       [ 87],
       [  9],
       [ 67],
       [232],
       [  8],
       [ 92],
       [  1],
       [ 95],
       [ 35],
       [ 44],
       [  7],
       [ 23],
       [  8],
       [246],
       [ 26],
       [207],
       [ 43],
       [  8],
       [  8],
       [ 93],
       [ 18],
       [ 15],
       [  3],
       [ 47],
      

In [174]:
input_seq,test_seq,y_true,y_hat=tf.constant(X_train),tf.constant(X_test),tf.constant(y_train),tf.constant(y_test)

In [175]:
input_seq

<tf.Tensor: shape=(155, 9), dtype=int32, numpy=
array([[ 54,  13,   2, ...,  91,  23,  13],
       [  6, 119,  10, ...,  41,   8, 419],
       [123,  18,   8, ..., 585,  10, 586],
       ...,
       [  4,   9,   5, ...,  36, 488,   2],
       [ 68, 170,  17, ...,  69,   7, 601],
       [  5,  70, 486, ...,   7,  27,  13]])>

In [176]:
tf.reduce_max(input_seq)+1

<tf.Tensor: shape=(), dtype=int32, numpy=605>

In [177]:
input=Input(shape=(seq_len-1,))
x=Embedding(input_dim=vocab_size+1,input_length=seq_len-1,output_dim=50,weights=[embedding_array],trainable=True)(input)
x=SimpleRNN(128)(x)
x=Dense(64)(x)
x=Dense(32)(x)
output=Dense(vocab_size,activation="softmax")(x)
model=Model(input,output)

C:\Users\user\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [178]:
model.summary()

Model: "functional_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_2 (InputLayer)      │ (None, 9)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ embedding_2 (Embedding)         │ (None, 9, 50)          │        30,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_2 (SimpleRNN)        │ (None, 128)            │        22,912 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 605)            │        19,965 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 83,513 (326.22 KB)

 Trainable params: 83,513 (326.22 KB)

 Non-trainable params: 0 (0.00 B)

In [179]:
model.compile(optimizer=Adam(0.01),loss=tf.keras.losses.sparse_categorical_crossentropy,metrics=['accuracy'])

In [180]:
model.fit(input_seq,y_true,epochs=10)

Epoch 1/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 7s 10ms/step - accuracy: 0.0121 - loss: 6.3084   
Epoch 2/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.0441 - loss: 4.8707 
Epoch 3/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.0454 - loss: 4.1334 
Epoch 4/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.0965 - loss: 3.9385
Epoch 5/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.1355 - loss: 3.5069
Epoch 6/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.1120 - loss: 3.2314 
Epoch 7/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.2302 - loss: 2.9230
Epoch 8/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.3553 - loss: 2.2507
Epoch 9/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5462 - loss: 1.6765 
Epoch 10/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5988 - loss: 1.2636 


In [181]:
model.evaluate(test_seq,y_hat)

3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.0000e+00 - loss: 13.1489  


[13.06098461151123, 0.0]

In [182]:
#input_text=["she was such a good person"]
#input_text=["he was such a good person and honestly speaking he did make good use of his"]
input_text=["Much more reproductive choice is now available to"]
#input_text=["can you please"]
#input_text=["marriage is such a beautiful"]
toks=tokenizer.texts_to_sequences(input_text)
ins=pad_sequences(toks,maxlen=seq_len-1)
input_tensor=tf.constant(ins)
input_tensor

<tf.Tensor: shape=(1, 9), dtype=int32, numpy=array([[  0, 114,  33, 150, 151,  12,  39, 241,   2]])>

In [183]:
pred=model.predict(input_tensor)
keys[vals.index(np.argmax(pred))]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 380ms/step


'the'

In [184]:
input_text[0]=input_text[0]+' '+keys[vals.index(np.argmax(pred))]
input_text[0]

'Much more reproductive choice is now available to the'

In [185]:
for i in range(10):
  toks=tokenizer.texts_to_sequences(input_text)
  ins=pad_sequences(toks,maxlen=seq_len-1)
  input_tensor=tf.constant(ins)
  pred=model.predict(input_tensor)
  input_text[0]=input_text[0]+' '+keys[vals.index(np.argmax(pred))]

print(input_text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
['Much more reproductive choice is now available to the ties seen gillespie is that influence that 1973 children reasons']


In [186]:
sort_pred=np.argsort(pred[0])
pred_words=np.flip(sort_pred[-5:])
for index in pred_words:
  print(keys[vals.index(index)])

reasons
in
be
gillespie
for
